name: client
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.8+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase dependencies
  cloud_firestore: 2.5.3
  firebase_auth: 3.1.1
  firebase_core: 1.6.0
  firebase_analytics: 8.3.2
  google_sign_in: ^4.4.4
  # flutter_facebook_login: ^3.0.0
  latlong: ^0.6.1

  # generator dependencies
  #  auto_route: ^0.6.9
  injectable: ^1.5.0
  get_it: 7.2.0
  freezed: 0.14.5
  freezed_annotation: 0.14.3

  # UI dependencies
  flutter_tindercard: ^0.2.0
  sliding_up_panel: ^2.0.0+1
  google_maps_flutter: 2.0.6
  flushbar: ^1.10.4
  responsive_builder: ^0.1.5
  responsive_framework: ^0.0.7
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.2.1

  # Other
  stacked: 2.2.5
  stacked_services: ^0.5.4+4
  form_field_validator: ^1.0.1
  intl:
  data_connection_checker: ^0.3.4
  shared_preferences: 2.0.8
  flutter_hooks: ^0.14.1
  dio: 4.0.0
  location: 4.0.0
  http_parser: 4.0.0
  flutter_settings_screens: ^0.2.1
  formz: ^0.3.2
  url_launcher: 6.1.4
  map_picker: ^0.0.3
  flutter_svg: ^0.23.0+1
  auto_size_text: ^3.0.0
  shimmer: ^2.0.0
  email_validator: ^1.0.6

  # icons
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0
  firebase_dynamic_links: ^2.0.9
  share_plus: ^4.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  #  auto_route_generator: ^0.6.9
  json_serializable: 5.0.2
  injectable_generator: 1.5.2
  flutter_launcher_icons: "0.9.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

dependency_overrides:
   logging:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/icon.png
